### ISSUE TITLE
HTML element passed in mouseOnDay is inconsistent with customDataSourceRenderer

### ISSUE THREAD

**Issue by cabintech** [year-calendar/js-year-calendar#12]
Not sure if by design or a bug, but the HTML element passed to the customDataSourceReneder is the content of the day cell. Altering it's CSS changes the visual representation. This is as expected.

The mouseOnDay event also passes the HTML element of the day - but it is the parent DIV and altering it's CSS has no visual effect. To alter the effect on mouse over you have to get the child element.

This seems inconsistent and the documentation makes no mention of it... you just have to know (or discover) that these methods are being passed different elements of the calendar widget. Would be much simpler if they were the same, or at least document exactly what is being passed to each one.

**Comment by Paul-DS** [comment]
You're right. I cannot change that because it will break compatibility with the previous version.

I updated the documentation, you can see the detail in [here](https://year-calendar.github.io/js-year-calendar/documentation), in **CalendarOptions** -> **customDataSourceRenderer** and **customDayRenderer**
