### ISSUE TITLE
A scroll bar appears because the calendar is not high enough

### ISSUE THREAD

**Issue by yukkes** [year-calendar/js-year-calendar#23]
If a month has 6 weeks (eg May 2020), a scroll bar will be displayed.
When I changed the height from 200px to 220px, the scrollbar disappeared.
https://github.com/year-calendar/js-year-calendar/blob/2b82507a6444fc7615e93bf3841b6c8390e7a32c/src/less/js-year-calendar.less#L130

**Comment by Paul-DS** [comment]
It depends of the style of your calendar.
This bug doesn't appear on the basic example: https://codepen.io/Paul-DS/pen/moWgbr
If your days are bigger than the basic example (because of a bigger `font-size`, `padding`, `margin`, etc...), the bug can indeed appear.

I'll try to see if I can make it dynamic.

**Comment by yukkes** [comment]
Thank you for your reply. The CodePen sample doesn't have scrollbars, so it was due to the CSS I applied.
Please close this issue.
